# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 14:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20171112_1421'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSubModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='carmodel',
            old_name='make',
            new_name='brand',
        ),
        migrations.AddField(
            model_name='carsubmodel',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.CarModel'),
        ),
    ]
