# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 16:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_engine'),
    ]

    operations = [
        migrations.AddField(
            model_name='engine',
            name='producer',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
