# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0003_remove_setup_car'),
        ('car', '0008_auto_20171125_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='setups',
            field=models.ManyToManyField(to='setup.Setup'),
        ),
        migrations.AddField(
            model_name='carsubmodel',
            name='setups',
            field=models.ManyToManyField(to='setup.Setup'),
        ),
    ]
