# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 20:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20171126_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carsubmodel',
            old_name='model',
            new_name='car_model',
        ),
    ]
