# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:38
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0011_auto_20171126_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='carsubmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
