# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0012_auto_20171127_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='carmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='carsubmodel',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
