# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('setup', '0009_setup_timestamp'),
        ('car', '0013_auto_20171128_1851'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='cars/')),
                ('is_main', models.BooleanField()),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Setup')),
            ],
        ),
    ]
