# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0014_carimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carimage',
            name='setup',
        ),
    ]
