# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 16:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0016_auto_20180123_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='stock_engines',
            field=models.ManyToManyField(blank=True, to='car.Engine'),
        ),
        migrations.AlterField(
            model_name='carsubmodel',
            name='stock_engines',
            field=models.ManyToManyField(blank=True, to='car.Engine'),
        ),
        migrations.AddField(
            model_name='carbrand',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsubmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
