# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 10:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0017_auto_20180126_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbrand',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 27, 10, 44, 12, 302441, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 27, 10, 44, 22, 334190, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='carsubmodel',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 27, 10, 44, 29, 917822, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
