# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 17:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='setups/')),
                ('is_main', models.BooleanField()),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Setup')),
            ],
        ),
    ]
