# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_setupimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setup',
            name='car',
        ),
    ]
