# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 12:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0004_auto_20171126_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='slug',
            field=models.SlugField(unique=True),
            preserve_default=False,
        ),
    ]
