# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0005_setup_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=200), unique=True),
        ),
    ]
