# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 17:42
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_auto_20171127_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
