# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('setup', '0007_auto_20171127_1742'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='setup',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='setupcomments',
            name='setup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Setup'),
        ),
        migrations.AddField(
            model_name='setupcomments',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
