# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 19:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_auto_20171128_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
