# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 06:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0009_setup_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SetupField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=300)),
                ('category', models.SmallIntegerField(choices=[(0, 'Engine'), (1, 'Drivetrain'), (2, 'Steering/Suspension'), (3, 'Brakes'), (4, 'Wheels'), (5, 'Exterior'), (6, 'Interior')])),
                ('setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='setup.Setup')),
            ],
        ),
        migrations.RenameModel(
            old_name='SetupComments',
            new_name='SetupComment',
        ),
    ]
