# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0010_auto_20180120_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='description',
            field=models.TextField(default=None,blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='power',
            field=models.IntegerField(default=None, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='rev_limit',
            field=models.IntegerField(default=None, blank=True, null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='setup',
            name='torque',
            field=models.IntegerField(default=None, blank=True, null=True),
            preserve_default=False,
        ),
    ]
