# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0011_setup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='weight',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='power',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='rev_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='setup',
            name='torque',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
