# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-20 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0015_remove_carimage_setup'),
        ('setup', '0012_auto_20180120_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='setup',
            name='engine',
            field=models.ForeignKey(default=3804, on_delete=django.db.models.deletion.CASCADE, to='car.Engine'),
            preserve_default=False,
        ),
    ]
