# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0014_setupvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupcomment',
            name='setup',
        ),
        migrations.RemoveField(
            model_name='setupcomment',
            name='user',
        ),
        migrations.AlterField(
            model_name='setup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.DeleteModel(
            name='SetupComment',
        ),
    ]
