# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0015_auto_20180122_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setupimage',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
