# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 12:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0017_setupimage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setupimage',
            name='is_main',
        ),
    ]
