# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0018_remove_setupimage_is_main'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='setupimage',
            order_with_respect_to='order',
        ),
    ]
