# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-31 11:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0019_auto_20180130_1337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='setupimage',
            options={'ordering': ['order']},
        ),
        migrations.AlterOrderWithRespectTo(
            name='setupimage',
            order_with_respect_to=None,
        ),
    ]
