# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
